package com.xapple.gankio.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xapple.gankio.data.model.DBModelTest;
import com.xapple.gankio.data.model.GankIO;

import com.xapple.gankio.db.DBModelTestDao;
import com.xapple.gankio.db.GankIODao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBModelTestDaoConfig;
    private final DaoConfig gankIODaoConfig;

    private final DBModelTestDao dBModelTestDao;
    private final GankIODao gankIODao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBModelTestDaoConfig = daoConfigMap.get(DBModelTestDao.class).clone();
        dBModelTestDaoConfig.initIdentityScope(type);

        gankIODaoConfig = daoConfigMap.get(GankIODao.class).clone();
        gankIODaoConfig.initIdentityScope(type);

        dBModelTestDao = new DBModelTestDao(dBModelTestDaoConfig, this);
        gankIODao = new GankIODao(gankIODaoConfig, this);

        registerDao(DBModelTest.class, dBModelTestDao);
        registerDao(GankIO.class, gankIODao);
    }
    
    public void clear() {
        dBModelTestDaoConfig.clearIdentityScope();
        gankIODaoConfig.clearIdentityScope();
    }

    public DBModelTestDao getDBModelTestDao() {
        return dBModelTestDao;
    }

    public GankIODao getGankIODao() {
        return gankIODao;
    }

}
